import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main> {children}</main>
        <footer className="bg-muted/50 py-12 ">
          <div className="container mx-auto px-4 text-center text-orange-800">
            <p>
              Made with ☕&🍫 by Ahmed{" "}
              <span className="text-yellow-700">:D</span>
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
